AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb

Rails/HasAndBelongsToMany:
  Exclude:
    - app/models/user.rb
    - app/models/team.rb
